apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pet-clinic

bases:
  - ../../base

patchesStrategicMerge:
  - namespace.yaml
  - petclinic-deployment.yaml
  - petclinic-route.yaml
  - petclinic-svc.yaml
  - petclinicdb-deploymentconfig.yaml
  - petclinicdb-pvc.yaml
  - petclinicdb-secret.yaml
  - petclinicdb-svc.yaml