resources:
  - namespace.yaml
  - petclinic-deployment.yaml
  - petclinic-route.yaml
  - petclinic-svc.yaml
  - petclinicdb-deploymentconfig.yaml
  - petclinicdb-pvc.yaml
  - petclinicdb-secret.yaml
  - petclinicdb-svc.yaml