
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: etherpad-acm-prd
  namespace: etherpad-acm-prd
  labels:
    app: etherpad-acm-prd
  annotations:
    apps.open-cluster-management.io/github-path: app-resources/etherpad/prd
spec:
  channel: etherpad-acm-prd/etherpad-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: prd-and-dr-cluster

