apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-dev

bases:
  - ../../pet-clinic-assets/base

resources:
  - namespace.yaml

images:
  - name: quay.io/pittar/petclinic
    newTag: petclinic-sandbox
