commonLabels:
  org: RHTE
commonAnnotations:
  note: Hello, I am at Istanbul
bases:
  - ../../base
patchesStrategicMerge:
  - namespace.yaml
  - petclinic-deployment.yaml
  - petclinic-route.yaml
  - petclinic-svc.yaml
  - petclinicdb-deploymentconfig.yaml
  - petclinicdb-pvc.yaml
  - petclinicdb-secret.yaml
  - petclinicdb-svc.yaml