apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pet-clinic-staging
  namespace: pet-clinic
  labels:
    deployment: hello
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: pet-clinic-assets/overlays/staging
spec:
  channel:  pet-clinic/pet-clinic-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: staging
