apiVersion: v1
name: spring-petclinic
description: A Helm chart for SpringBoot PetClinic
version: 0.1.0
appVersion: "1.0"
home: https://github.com/axdotl/spring-petclinic-helm
sources:
  - https://github.com/spring-petclinic/spring-petclinic-angularjs